#!/bin/zsh
W="\033[01;37m"
B="\033[30;44m"
BB="\033[34m"
Y="\033[30;43m"
YY="\033[33m"
R="\033[30;41m"
X="\033[0m"

IPADDR=$(ifconfig | awk '($1 == "inet") && ($2 !~ /127.0.0.1/) { print $2 }' | sed 's/addr\://' | tail -1)

echo  "$B              $Y $USER@$(uname -n) $R $IPADDR $X"
echo ""
echo "# $(uname -srvm)"
echo "#$(uptime)"

if command -v tmux; then
echo "$BB# TMUX sessions: - $X $(tmux list-sessions)"
fi

echo "$BB# --- SSH Logins --- $X"
if [[ "$OSTYPE" == "darwin"* ]]; then
last
else
last --since "2 days ago"  --dns --fullnames -x | grep -v "0.0.0.0" | grep -v "begins" | grep -v tmux |  head -20
fi


