name: ShellCheck

on:
  pull_request:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
    
    - name: Find and check shell scripts
      run: |
        find . -type f -name "*.sh" -o -name "*.bash" -o -name "*.ksh" -o -name "*.dash" | \
        while read file; do
          shellcheck 
